name             'dev_java'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures dev_java'
long_description 'Installs/Configures dev_java'
version          '0.1.0'
